const searchList = [
  // Personal Development & Growth (100 keywords)
  "productivity", "habits", "mindset", "discipline", "focus", "goals", "success", "achievement", 
  "motivation", "willpower", "resilience", "grit", "perseverance", "confidence", "courage",
  "determination", "ambition", "drive", "passion", "purpose", "vision", "excellence", "mastery",
  "growth", "development", "improvement", "transformation", "change", "evolution", "progress",
  "advancement", "breakthrough", "potential", "optimization", "enhancement", "upgrade", "level",
  "performance", "effectiveness", "efficiency", "results", "outcomes", "impact", "influence",
  "power", "strength", "force", "energy", "vitality", "vigor", "intensity", "momentum",
  "acceleration", "velocity", "speed", "rapid", "fast", "quick", "instant", "immediate",
  "revolutionary", "radical", "extreme", "maximum", "ultimate", "supreme", "elite", "premium",
  "superior", "advanced", "cutting", "edge", "innovative", "creative", "genius", "brilliant",
  "exceptional", "extraordinary", "remarkable", "outstanding", "phenomenal", "incredible",
  "amazing", "spectacular", "magnificent", "superb", "fantastic", "wonderful", "marvelous",
  "fabulous", "awesome", "perfect", "flawless", "impeccable", "pristine", "pure", "refined",
  "sophisticated", "elegant", "graceful", "smooth", "seamless", "effortless", "natural",
  "organic", "authentic", "genuine", "real", "true", "honest", "transparent", "clear",

  // Mental & Emotional Mastery (100 keywords)
  "psychology", "cognitive", "mindfulness", "meditation", "stoicism", "philosophy", "wisdom",
  "emotional", "intelligence", "mental", "clarity", "consciousness", "awareness", "presence",
  "attention", "concentration", "contemplation", "reflection", "introspection", "insight",
  "understanding", "comprehension", "knowledge", "learning", "education", "training", "skill",
  "expertise", "competence", "proficiency", "fluency", "mastery", "command", "control",
  "regulation", "management", "balance", "harmony", "peace", "calm", "serenity", "tranquility",
  "relaxation", "stress", "anxiety", "worry", "fear", "doubt", "uncertainty", "confusion",
  "overwhelm", "burnout", "fatigue", "exhaustion", "recovery", "restoration", "renewal",
  "rejuvenation", "revitalization", "regeneration", "healing", "therapy", "counseling",
  "coaching", "mentoring", "guidance", "support", "assistance", "help", "aid", "relief",
  "comfort", "solace", "peace", "joy", "happiness", "bliss", "ecstasy", "euphoria",
  "satisfaction", "fulfillment", "contentment", "gratitude", "appreciation", "thankfulness",
  "positivity", "optimism", "hope", "faith", "belief", "trust", "confidence", "certainty",
  "conviction", "determination", "resolve", "commitment", "dedication", "devotion", "loyalty",
  "integrity", "honor", "dignity", "respect", "admiration", "reverence", "worship", "love",

  // Health & Vitality (100 keywords)
  "longevity", "biohacking", "nutrition", "fitness", "sleep", "energy", "vitality", "wellness",
  "health", "performance", "optimization", "recovery", "strength", "endurance", "flexibility",
  "mobility", "agility", "speed", "power", "conditioning", "training", "exercise", "workout",
  "bodybuilding", "weightlifting", "cardio", "aerobic", "anaerobic", "yoga", "pilates",
  "stretching", "massage", "therapy", "treatment", "healing", "medicine", "natural", "holistic",
  "alternative", "complementary", "preventive", "lifestyle", "diet", "eating", "food",
  "superfoods", "supplements", "vitamins", "minerals", "nutrients", "antioxidants", "probiotics",
  "fasting", "intermittent", "ketogenic", "paleo", "vegan", "vegetarian", "raw", "organic",
  "detox", "cleanse", "purification", "elimination", "toxins", "inflammation", "immune",
  "system", "immunity", "resistance", "defense", "protection", "safety", "security",
  "prevention", "maintenance", "care", "self", "body", "mind", "spirit", "soul",
  "breath", "breathing", "oxygen", "air", "water", "hydration", "circulation", "blood",
  "heart", "cardiovascular", "brain", "neurological", "nervous", "hormonal", "endocrine",
  "metabolic", "digestive", "gut", "microbiome", "cellular", "molecular", "genetic", "DNA",
  "epigenetic", "regenerative", "anti", "aging", "youth", "fountain", "immortal", "eternal",

  // Wealth & Financial Freedom (100 keywords)
  "investing", "wealth", "money", "financial", "entrepreneurship", "business", "passive", 
  "income", "economics", "trading", "cryptocurrency", "real", "estate", "budgeting", "frugal",
  "saving", "spending", "debt", "credit", "loans", "mortgage", "insurance", "retirement",
  "pension", "401k", "IRA", "stocks", "bonds", "mutual", "funds", "ETF", "portfolio",
  "diversification", "risk", "management", "return", "profit", "loss", "gain", "compound",
  "interest", "dividends", "capital", "assets", "liabilities", "net", "worth", "cash",
  "flow", "liquidity", "equity", "ownership", "property", "rental", "lease", "tenant",
  "landlord", "flip", "wholesale", "fix", "rehab", "development", "construction", "zoning",
  "market", "analysis", "valuation", "appraisal", "negotiation", "contract", "deal", "closing",
  "financing", "leverage", "loan", "mortgage", "refinance", "equity", "line", "credit",
  "banking", "financial", "planning", "advisor", "consultant", "accountant", "tax", "strategy",
  "offshore", "trust", "estate", "inheritance", "legacy", "generational", "dynasty", "empire",
  "millionaire", "billionaire", "rich", "wealthy", "affluent", "prosperous", "abundant",
  "luxury", "lifestyle", "freedom", "independence", "security", "stability", "growth",
  "expansion", "scaling", "multiplication", "exponential", "geometric", "compound", "viral",

  // Relationships & Communication (100 keywords)
  "influence", "persuasion", "charisma", "networking", "leadership", "communication", "social",
  "relationships", "dating", "marriage", "parenting", "teamwork", "negotiation", "public",
  "speaking", "presentation", "rhetoric", "eloquence", "articulation", "expression", "voice",
  "tone", "body", "language", "nonverbal", "gesture", "posture", "eye", "contact",
  "listening", "hearing", "understanding", "empathy", "compassion", "sympathy", "kindness",
  "generosity", "giving", "sharing", "caring", "loving", "affection", "intimacy", "romance",
  "attraction", "magnetism", "charm", "appeal", "likability", "popularity", "fame", "celebrity",
  "recognition", "reputation", "brand", "image", "impression", "perception", "opinion",
  "feedback", "criticism", "praise", "compliment", "encouragement", "support", "motivation",
  "inspiration", "influence", "impact", "effect", "change", "transformation", "conversion",
  "persuasion", "conviction", "belief", "trust", "credibility", "authority", "expertise",
  "knowledge", "wisdom", "experience", "skill", "talent", "ability", "capacity", "potential",
  "power", "control", "dominance", "submission", "cooperation", "collaboration", "partnership",
  "alliance", "team", "group", "community", "society", "culture", "tradition", "custom",
  "norm", "standard", "expectation", "requirement", "obligation", "responsibility", "duty",

  // Learning & Intelligence (100 keywords)
  "learning", "memory", "speed", "reading", "critical", "thinking", "creativity", "innovation",
  "problem", "solving", "decision", "making", "strategic", "analytical", "genius", "mastery",
  "intelligence", "IQ", "EQ", "cognitive", "mental", "brain", "mind", "consciousness",
  "awareness", "attention", "focus", "concentration", "contemplation", "meditation", "mindfulness",
  "study", "research", "investigation", "exploration", "discovery", "invention", "creation",
  "design", "development", "construction", "building", "crafting", "making", "producing",
  "manufacturing", "engineering", "technology", "science", "mathematics", "physics", "chemistry",
  "biology", "psychology", "philosophy", "logic", "reasoning", "deduction", "induction",
  "analysis", "synthesis", "evaluation", "assessment", "judgment", "discernment", "wisdom",
  "knowledge", "information", "data", "facts", "truth", "reality", "evidence", "proof",
  "demonstration", "explanation", "interpretation", "understanding", "comprehension", "insight",
  "revelation", "enlightenment", "awakening", "realization", "recognition", "identification",
  "classification", "categorization", "organization", "structure", "system", "method",
  "technique", "strategy", "tactic", "approach", "way", "path", "route", "direction",
  "guidance", "instruction", "teaching", "education", "training", "coaching", "mentoring",
  "tutoring", "lecturing", "presenting", "demonstrating", "showing", "explaining", "clarifying",

  // Time & Life Management (100 keywords)
  "time", "management", "organization", "systems", "efficiency", "automation", "minimalism",
  "essentialism", "prioritization", "planning", "scheduling", "work", "life", "balance",
  "productivity", "effectiveness", "optimization", "streamlining", "simplification", "reduction",
  "elimination", "focus", "concentration", "attention", "presence", "mindfulness", "awareness",
  "clarity", "purpose", "intention", "goal", "objective", "target", "outcome", "result",
  "achievement", "accomplishment", "success", "victory", "triumph", "win", "progress",
  "advancement", "improvement", "enhancement", "upgrade", "evolution", "transformation",
  "change", "adaptation", "adjustment", "modification", "alteration", "revision", "update",
  "renewal", "refresh", "restart", "reboot", "reset", "beginning", "start", "launch",
  "initiation", "commencement", "opening", "introduction", "first", "initial", "primary",
  "fundamental", "basic", "essential", "core", "central", "main", "principal", "key",
  "critical", "crucial", "vital", "important", "significant", "major", "substantial",
  "considerable", "notable", "remarkable", "outstanding", "exceptional", "extraordinary",
  "unique", "special", "rare", "precious", "valuable", "worthwhile", "beneficial", "useful",
  "practical", "functional", "operational", "working", "active", "dynamic", "energetic",
  "vigorous", "powerful", "strong", "robust", "solid", "stable", "secure", "safe",

  // Advanced Psychology & Neuroscience (100 keywords)
  "neuroscience", "neuroplasticity", "synapse", "neurotransmitter", "dopamine", "serotonin",
  "oxytocin", "endorphin", "cortisol", "adrenaline", "noradrenaline", "GABA", "acetylcholine",
  "limbic", "amygdala", "hippocampus", "prefrontal", "cortex", "cerebellum", "brainstem",
  "nervous", "autonomic", "sympathetic", "parasympathetic", "vagus", "nerve", "meditation",
  "mindfulness", "consciousness", "subconscious", "unconscious", "cognitive", "behavioral",
  "therapy", "CBT", "DBT", "ACT", "mindset", "belief", "thought", "pattern", "habit",
  "conditioning", "reinforcement", "reward", "punishment", "motivation", "drive", "instinct",
  "emotion", "feeling", "mood", "temperament", "personality", "character", "trait",
  "psychoanalysis", "psychotherapy", "counseling", "coaching", "NLP", "hypnosis", "trance",
  "visualization", "imagery", "affirmation", "mantra", "prayer", "ritual", "ceremony",
  "flow", "zone", "peak", "performance", "optimal", "experience", "transcendence", "mystical",
  "spiritual", "enlightenment", "awakening", "consciousness", "awareness", "presence",
  "attention", "focus", "concentration", "contemplation", "reflection", "introspection",
  "self", "awareness", "knowledge", "understanding", "insight", "wisdom", "intelligence",
  "intuition", "instinct", "gut", "feeling", "sixth", "sense", "perception", "observation",
  "notice", "recognize", "identify", "distinguish", "differentiate", "discriminate", "judge",

  // Spirituality & Philosophy (100 keywords)
  "spirituality", "philosophy", "metaphysics", "ontology", "epistemology", "ethics", "morality",
  "virtue", "wisdom", "truth", "reality", "existence", "being", "consciousness", "awareness",
  "enlightenment", "awakening", "transcendence", "transformation", "evolution", "ascension",
  "meditation", "contemplation", "prayer", "worship", "devotion", "faith", "belief", "trust",
  "hope", "love", "compassion", "kindness", "forgiveness", "grace", "mercy", "peace",
  "harmony", "unity", "oneness", "connection", "relationship", "communion", "intimacy",
  "divine", "sacred", "holy", "blessed", "pure", "innocent", "perfect", "complete",
  "whole", "integrated", "balanced", "centered", "grounded", "rooted", "stable", "secure",
  "ancient", "wisdom", "tradition", "teaching", "scripture", "text", "book", "manual",
  "guide", "path", "way", "journey", "quest", "search", "seek", "find", "discover",
  "Buddhism", "Christianity", "Islam", "Judaism", "Hinduism", "Taoism", "Zen", "Sufism",
  "Kabbalah", "mysticism", "esotericism", "occultism", "magic", "alchemy", "astrology",
  "numerology", "tarot", "divination", "prophecy", "vision", "dream", "symbol", "archetype",
  "myth", "legend", "story", "narrative", "parable", "allegory", "metaphor", "analogy",
  "example", "illustration", "demonstration", "proof", "evidence", "sign", "miracle",
  "wonder", "mystery", "secret", "hidden", "revealed", "unveiled", "exposed", "manifest",

  // Technology & Innovation (100 keywords)
  "technology", "innovation", "invention", "creation", "design", "engineering", "science",
  "research", "development", "breakthrough", "discovery", "advancement", "progress", "evolution",
  "artificial", "intelligence", "AI", "machine", "learning", "deep", "neural", "network",
  "algorithm", "data", "analytics", "big", "cloud", "computing", "quantum", "blockchain",
  "cryptocurrency", "bitcoin", "ethereum", "NFT", "metaverse", "virtual", "reality", "VR",
  "augmented", "AR", "mixed", "MR", "robotics", "automation", "IoT", "internet", "things",
  "smartphone", "mobile", "app", "software", "hardware", "computer", "laptop", "tablet",
  "wearable", "smartwatch", "fitness", "tracker", "biometric", "sensor", "monitoring",
  "cybersecurity", "privacy", "encryption", "protection", "safety", "security", "hacking",
  "programming", "coding", "development", "web", "mobile", "game", "application", "platform",
  "framework", "library", "database", "server", "hosting", "domain", "website", "blog",
  "social", "media", "network", "community", "sharing", "collaboration", "communication",
  "video", "conference", "remote", "work", "telecommuting", "digital", "nomad", "freelance",
  "gig", "economy", "startup", "unicorn", "venture", "capital", "funding", "investment",
  "IPO", "acquisition", "merger", "partnership", "alliance", "ecosystem", "disruption",
  "transformation", "digitization", "optimization", "efficiency", "productivity", "performance",

  // Career & Professional Development (100 keywords)
  "career", "profession", "job", "work", "employment", "occupation", "vocation", "calling",
  "purpose", "mission", "vision", "goal", "ambition", "aspiration", "dream", "achievement",
  "success", "advancement", "promotion", "raise", "salary", "compensation", "benefits",
  "skills", "competency", "expertise", "experience", "qualification", "certification",
  "education", "training", "development", "learning", "growth", "improvement", "enhancement",
  "networking", "relationship", "connection", "contact", "referral", "recommendation",
  "interview", "resume", "CV", "portfolio", "profile", "brand", "reputation", "image",
  "leadership", "management", "supervision", "delegation", "responsibility", "authority",
  "teamwork", "collaboration", "cooperation", "communication", "presentation", "negotiation",
  "sales", "marketing", "advertising", "promotion", "branding", "customer", "client",
  "service", "satisfaction", "quality", "excellence", "performance", "productivity",
  "efficiency", "effectiveness", "results", "outcomes", "metrics", "KPI", "ROI",
  "strategy", "planning", "execution", "implementation", "project", "program", "initiative",
  "innovation", "creativity", "problem", "solving", "decision", "making", "critical",
  "thinking", "analysis", "research", "investigation", "evaluation", "assessment",
  "entrepreneur", "startup", "business", "company", "corporation", "organization",
  "industry", "market", "competition", "advantage", "differentiation", "positioning",
  "consultant", "advisor", "coach", "mentor", "guide", "teacher", "trainer", "speaker"
];

export default searchList




